import { RequestHandler } from "express";
import fs from "fs";
import path from "path";
import { parse } from "csv-parse/sync";
import {
  InventoryRecommendation,
  InventoryRecommendationsResponse,
} from "@shared/api";

/**
 * Read inventory recommendations from CSV file
 * CSV is generated by FlowStock-AI inventory optimization model
 */
export const handleInventoryRecommendations: RequestHandler = (req, res) => {
  try {
    const csvPath = path.join(
      process.cwd(),
      "..",
      "..",
      "FlowStock-AI",
      "artifacts",
      "inventory_ai_recommendations.csv"
    );

    // Fallback path for different directory structures
    const fallbackPath = path.join(
      process.cwd(),
      "..",
      "FlowStock-AI",
      "artifacts",
      "inventory_ai_recommendations.csv"
    );

    let filePath = csvPath;
    if (!fs.existsSync(filePath) && fs.existsSync(fallbackPath)) {
      filePath = fallbackPath;
    }

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({
        error: "Inventory recommendations not found. Please run training first.",
        csvPath: filePath,
      });
    }

    const fileContent = fs.readFileSync(filePath, "utf-8");
    const records = parse(fileContent, {
      columns: true,
      skip_empty_lines: true,
    }) as any[];

    // Convert to proper types and parse numeric values
    const data: InventoryRecommendation[] = records.map((row) => ({
      id: parseInt(row.id, 10),
      product_id: parseInt(row.product_id, 10),
      product_name: row.product_name,
      sku: row.sku,
      product_category: row.product_category,
      warehouse_id: parseInt(row.warehouse_id, 10),
      warehouse_name: row.warehouse_name,
      current_stock: parseInt(row.current_stock, 10),
      predicted_demand_14d: parseInt(row.predicted_demand_14d, 10),
      reorder_point: parseInt(row.reorder_point, 10),
      target_stock: parseInt(row.target_stock, 10),
      shortage: parseInt(row.shortage, 10),
      status: row.status as "Healthy" | "Critical" | "Overstock",
      recommended_action: row.recommended_action as
        | "None"
        | "Transfer"
        | "Discount"
        | "Order",
    }));

    // Optional: filter and sort
    const warehouse = req.query.warehouse as string | undefined;
    const category = req.query.category as string | undefined;
    const status = req.query.status as string | undefined;
    const action = req.query.action as string | undefined;

    let filtered = data;

    if (warehouse && warehouse !== "All Warehouses") {
      filtered = filtered.filter(
        (item) =>
          item.warehouse_name.toLowerCase() === warehouse.toLowerCase()
      );
    }

    if (category && category !== "All Categories") {
      filtered = filtered.filter(
        (item) =>
          item.product_category.toLowerCase() === category.toLowerCase()
      );
    }

    if (status && status !== "All Statuses") {
      filtered = filtered.filter((item) => item.status === status);
    }

    if (action && action !== "All Actions") {
      filtered = filtered.filter(
        (item) => item.recommended_action === action
      );
    }

    // Sort by ID
    filtered = filtered.sort((a, b) => a.id - b.id);

    const response: InventoryRecommendationsResponse = {
      data: filtered,
      total: filtered.length,
    };

    res.json(response);
  } catch (error) {
    console.error("Error reading inventory recommendations:", error);
    res.status(500).json({
      error: "Failed to read inventory recommendations",
      message: error instanceof Error ? error.message : "Unknown error",
    });
  }
};
